dist: trusty
addons:
  chrome: stable
language: node_js
node_js:
  - stable
env:
  - CODECLIMATE_REPO_TOKEN=59198deafe4cc9d533a49973750025ad91928e95f55eafee8f94b1d64b60d2bc
  - CODECLIMATE_API_HOST=https://codebeat.co/webhooks/code_coverage CODECLIMATE_REPO_TOKEN=5a3a6779-ae1f-4b31-9091-d24503a6b2d7
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - yarn config set registry "https://registry.npmjs.org"
  - yarn global add greenkeeper-lockfile@1
  - yarn global add codeclimate-test-reporter
before_script:
  - greenkeeper-lockfile-update
script:
  - yarn test
after_script:
  - greenkeeper-lockfile-upload
after_success:
  - codeclimate-test-reporter < coverage/lcov.info
